version: 2
jobs:
  build-all-arch:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: make
      - store_artifacts:
          path: out
      - persist_to_workspace:
          root: .
          paths:
            - out
  release-to-github:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Setup ghr
          command: |
            sudo wget -q https://github.com/tcnksm/ghr/releases/download/v0.10.0/ghr_v0.10.0_linux_amd64.tar.gz
            sudo tar xzf ghr_v0.10.0_linux_amd64.tar.gz --strip-components=1 -C /usr/local/bin ghr_v0.10.0_linux_amd64/ghr
            sudo rm -rf ghr_v0.10.0_linux_amd64.tar.gz
      - run: ghr ${CIRCLE_TAG} out/

workflows:
  version: 2
  build-and-release:
    jobs:
      - build-all-arch:
          filters:
            tags:
              only: /.*/
      - release-to-github:
          requires:
            - build-all-arch
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
